name: Semantic Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: yarn semantic-release
